name: Documentation_Preview
on:
  pull_request:
    branches: [ develop ]

permissions:
  pull-requests: write

jobs:
  documentation-links:
    runs-on: ubuntu-latest
    steps:
      - uses: readthedocs/actions/preview@v1
        with:
          project-slug: "openfl"
