# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: TaskRunner (Eden Compression)

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    if: (github.event.pull_request.draft == false && contains(github.event.pull_request.labels.*.name, 'eden_compression'))
    strategy:
      matrix:
       os: ['ubuntu-latest', 'windows-latest']
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Test TaskRunner API with Eden Compression
      run: |
        python -m tests.github.test_hello_federation --template torch/mnist_eden_compression --fed_workspace aggregator --col1 col1 --col2 col2  --rounds-to-train 3
